sonar.projectKey=agendat-backoffice
sonar.organization=la_teva_org

# On està el codi i on estan els tests
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.tsx,**/*.spec.js

# Excloure carpetes que no volem analitzar
sonar.exclusions=node_modules/**, dist/**, public/**

# Ruta al fitxer de cobertura que generarà Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
